{
 "title": "Weather Station",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "station",
    "label": "Station",
    "query": {
     "query": "label_values(ecowitt_temp,target)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ecowitt_temp{sensor=\"outdoor\",target=~\"$station.*\"})",
     "legendFormat": "Temperature Outdoor"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ecowitt_temp{sensor=\"indoor\",target=~\"$station.*\"})",
     "legendFormat": "Temperature Outdoor"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ecowitt_temp{sensor=\"ch1\",target=~\"$station.*\"})",
     "legendFormat": "Enclosure Temperature"
    }
   ]
  },
  {
   "title": "Barometer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "avg(ecowitt_barom{sensor=\"relative\",target=~\"$station.*\"})",
     "legendFormat": "Barometer"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_rain{sensor=\"rainrate\",target=~\"$station.*\"}",
     "legendFormat": "Current Rain"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_barom{sensor=\"absolute\",target=~\"$station.*\"}",
     "legendFormat": "Barometer"
    },
    {
     "expr": "delta(ecowitt_barom{sensor=\"absolute\",target=~\"$station.*\"}[1h])",
     "legendFormat": "Change -1h"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(ecowitt_temp{sensor=\"indoor\",target=~\"$station.*\"})",
     "legendFormat": "Temperature Indoor"
    },
    {
     "expr": "avg(ecowitt_temp{sensor=\"outdoor\",target=~\"$station.*\"})",
     "legendFormat": "Temperature Outdoor"
    },
    {
     "expr": "avg(ecowitt_temp{sensor=\"ch1\",target=~\"$station.*\"})",
     "legendFormat": "Temperature Enclosure"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ecowitt_winddir{target=~\"$station.*\"}",
     "legendFormat": "Wind Dir"
    },
    {
     "expr": "quantile_over_time(0.5, ecowitt_winddir{target=~\"$station.*\"}[20m] offset -10m)",
     "legendFormat": "Wind Dir p50"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "ecowitt_rain{sensor=\"dailyrain\",target=~\"$station.*\"}",
     "legendFormat": "Rain today"
    },
    {
     "expr": "ecowitt_rain{sensor=\"monthlyrain\",target=~\"$station.*\"}",
     "legendFormat": "Monthly rain"
    },
    {
     "expr": "ecowitt_rain{sensor=\"yearlyrain\",target=~\"$station.*\"}",
     "legendFormat": "Yearly Rain"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg(ecowitt_humidity{sensor=\"outdoor\",target=~\"$station.*\"})",
     "legendFormat": "Humidity Out"
    },
    {
     "expr": "avg(ecowitt_humidity{sensor=\"indoor\",target=~\"$station.*\"})",
     "legendFormat": "Humidity In"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "avg(ecowitt_windspeed{sensor=\"windgust\",target=~\"$station.*\"})",
     "legendFormat": "Wind Gusts"
    },
    {
     "expr": "avg(avg_over_time(ecowitt_windspeed{sensor=\"windspeed\",target=~\"$station.*\"}[$__rate_interval]))",
     "legendFormat": "Wind Speed"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_humidity{sensor=\"outdoor\",target=~\"$station.*\"}",
     "legendFormat": "Humidity Out"
    },
    {
     "expr": "ecowitt_humidity{sensor=\"indoor\",target=~\"$station.*\"}",
     "legendFormat": "Humidity In"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecowitt_uv{target=~\"$station.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ecowitt_solarradiation{target=~\"$station.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lightning Strikes/Distance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "avg(ecowitt_lightning{target=~\"$station.*\"} * (changes(ecowitt_lightning{target=~\"$station.*\"} [30m]) > bool 0)  != 0)\n",
     "legendFormat": "Distance (km)"
    },
    {
     "expr": "avg(increase(ecowitt_lightning_num{target=~\"$station.*\"}[30m]))",
     "legendFormat": "Striks"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg(ecowitt_wh90{sensor=\"ws90cap_volt\",target=~\"$station.*\"})",
     "legendFormat": "Capacitor"
    },
    {
     "expr": "avg(ecowitt_batterystatus{sensor=\"wh90batt\",target=~\"$station.*\"})",
     "legendFormat": "Battery wh90"
    }
   ]
  },
  {
   "title": "Radiation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "expr": "avg(ecowitt_solarradiation{target=~\"$station.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "avg(ecowitt_rain{sensor=\"rainrate\",target=~\"$station.*\"})",
     "legendFormat": "Rain Rate (mm/h)"
    },
    {
     "expr": "avg(ecowitt_rain{sensor=\"dailyrain\",target=~\"$station.*\"})",
     "legendFormat": "Rain today (mm)"
    },
    {
     "expr": "avg(ecowitt_rain{sensor=\"monthlyrain\",target=~\"$station.*\"})",
     "legendFormat": "Monthly (mm)"
    },
    {
     "expr": "avg(ecowitt_rain{sensor=\"yearlyrain\",target=~\"$station.*\"})",
     "legendFormat": "yearly (mm)"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "avg(ecowitt_rain{sensor=\"rainrate\",target=~\"$station.*\"})",
     "legendFormat": "Rain Rate (mm/h)"
    },
    {
     "expr": "avg(ecowitt_rain{sensor=\"dailyrain\",target=~\"$station.*\"})",
     "legendFormat": "Rain today (mm)"
    }
   ]
  }
 ]
}